server:
  port: 8081

team:
  leader: "xym"
  phone: "15062106761"
  age: 3
  createDate: "2019-09-01"


custom:
  qrcode:
    content: "https://www.baidu.com"

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.qq.com # 邮件服务器地址，QQ邮箱的SMTP服务器固定写法
    username: 2464668802@qq.com # 发件人邮箱地址
    password: jgsiquhhlpjwdidf # 客户端授权码（不是登录密码，需在QQ邮箱里开通SMTP服务获取）
    properties.mail.smtp.ssl.enable: true # 是否启用SSL加密，465端口必须true